// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/challenge-github-events/internal/github (interfaces: EventsFetcher,CommitStatsFetcher)
//
// Generated by this command:
//
//	mockgen -destination client_mock.gen.go -package github . EventsFetcher,CommitStatsFetcher
//

// Package github is a generated GoMock package.
package github

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockEventsFetcher is a mock of EventsFetcher interface.
type MockEventsFetcher struct {
	ctrl     *gomock.Controller
	recorder *MockEventsFetcherMockRecorder
	isgomock struct{}
}

// MockEventsFetcherMockRecorder is the mock recorder for MockEventsFetcher.
type MockEventsFetcherMockRecorder struct {
	mock *MockEventsFetcher
}

// NewMockEventsFetcher creates a new mock instance.
func NewMockEventsFetcher(ctrl *gomock.Controller) *MockEventsFetcher {
	mock := &MockEventsFetcher{ctrl: ctrl}
	mock.recorder = &MockEventsFetcherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEventsFetcher) EXPECT() *MockEventsFetcherMockRecorder {
	return m.recorder
}

// FetchEvents mocks base method.
func (m *MockEventsFetcher) FetchEvents(ctx context.Context, etag string) ([]Event, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchEvents", ctx, etag)
	ret0, _ := ret[0].([]Event)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FetchEvents indicates an expected call of FetchEvents.
func (mr *MockEventsFetcherMockRecorder) FetchEvents(ctx, etag any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchEvents", reflect.TypeOf((*MockEventsFetcher)(nil).FetchEvents), ctx, etag)
}

// MockCommitStatsFetcher is a mock of CommitStatsFetcher interface.
type MockCommitStatsFetcher struct {
	ctrl     *gomock.Controller
	recorder *MockCommitStatsFetcherMockRecorder
	isgomock struct{}
}

// MockCommitStatsFetcherMockRecorder is the mock recorder for MockCommitStatsFetcher.
type MockCommitStatsFetcherMockRecorder struct {
	mock *MockCommitStatsFetcher
}

// NewMockCommitStatsFetcher creates a new mock instance.
func NewMockCommitStatsFetcher(ctrl *gomock.Controller) *MockCommitStatsFetcher {
	mock := &MockCommitStatsFetcher{ctrl: ctrl}
	mock.recorder = &MockCommitStatsFetcherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCommitStatsFetcher) EXPECT() *MockCommitStatsFetcherMockRecorder {
	return m.recorder
}

// GetCommitStats mocks base method.
func (m *MockCommitStatsFetcher) GetCommitStats(ctx context.Context, owner, repo, ref string) (*CommitStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCommitStats", ctx, owner, repo, ref)
	ret0, _ := ret[0].(*CommitStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCommitStats indicates an expected call of GetCommitStats.
func (mr *MockCommitStatsFetcherMockRecorder) GetCommitStats(ctx, owner, repo, ref any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCommitStats", reflect.TypeOf((*MockCommitStatsFetcher)(nil).GetCommitStats), ctx, owner, repo, ref)
}
