// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/challenge-github-events/internal/store (interfaces: Store)
//
// Generated by this command:
//
//	mockgen -destination store_mock.gen.go -package store . Store
//

// Package store is a generated GoMock package.
package store

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockStore is a mock of Store interface.
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
	isgomock struct{}
}

// MockStoreMockRecorder is the mock recorder for MockStore.
type MockStoreMockRecorder struct {
	mock *MockStore
}

// NewMockStore creates a new mock instance.
func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStore) EXPECT() *MockStoreMockRecorder {
	return m.recorder
}

// EventsSeenCount mocks base method.
func (m *MockStore) EventsSeenCount(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EventsSeenCount", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EventsSeenCount indicates an expected call of EventsSeenCount.
func (mr *MockStoreMockRecorder) EventsSeenCount(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EventsSeenCount", reflect.TypeOf((*MockStore)(nil).EventsSeenCount), ctx)
}

// GlobalNetLines mocks base method.
func (m *MockStore) GlobalNetLines(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GlobalNetLines", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GlobalNetLines indicates an expected call of GlobalNetLines.
func (mr *MockStoreMockRecorder) GlobalNetLines(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GlobalNetLines", reflect.TypeOf((*MockStore)(nil).GlobalNetLines), ctx)
}

// InsertCommitStats mocks base method.
func (m *MockStore) InsertCommitStats(ctx context.Context, stats *CommitStatsRow) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertCommitStats", ctx, stats)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertCommitStats indicates an expected call of InsertCommitStats.
func (mr *MockStoreMockRecorder) InsertCommitStats(ctx, stats any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertCommitStats", reflect.TypeOf((*MockStore)(nil).InsertCommitStats), ctx, stats)
}

// InsertPushEvent mocks base method.
func (m *MockStore) InsertPushEvent(ctx context.Context, event *PushEventRow) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertPushEvent", ctx, event)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertPushEvent indicates an expected call of InsertPushEvent.
func (mr *MockStoreMockRecorder) InsertPushEvent(ctx, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertPushEvent", reflect.TypeOf((*MockStore)(nil).InsertPushEvent), ctx, event)
}

// Ping mocks base method.
func (m *MockStore) Ping(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockStoreMockRecorder) Ping(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockStore)(nil).Ping), ctx)
}
